import { CVs as CV } from './CV';
import { Jobs as Job } from './Job';
import { Plans as Plan } from './Plan';
import { Profiles as Profile } from './Profile';
import { Roles as Role } from './Role';
import { Transactions as Transaction } from './Transaction';
import { Users as User } from './User';
import { Views as View } from './View';
export const test = 'asd';
export const Profiles = Profile;
export const Users = User;
export const Jobs = Job;
export const Plans = Plan;
export const Roles = Role;
export const Views = View;
